HMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from hotel.api_views import RoomViewSet

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'rooms', RoomViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+=router.urls

hotel/urls.py
from django.urls import path
from .views import BookingListView, RoomDetailView, CancelBookingView, CheckoutView, success_view, cancel_view, BookingFormView, contact_us



app_name = 'hotel'

urlpatterns = [
    path('', BookingFormView.as_view(), name='BookingFormView'),
    path('booking_list/', BookingListView.as_view(), name='BookingListView'),
    path('room/<category>', RoomDetailView.as_view(), name='RoomDetailView'),
    path('booking/cancel/<pk>', CancelBookingView.as_view(),
         name='CancelBookingView'),
    path('checkout/', CheckoutView.as_view(), name='CheckoutView'),
    path('success/', success_view, name='success_view'),
    path('cancel/', cancel_view, name='cancel_view'),
    path('contact-us/', contact_us, name="contact_us")

]

hotel/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy

# Create your models here.


class RoomCategory(models.Model):
    category = models.CharField(max_length=50)
    rate = models.FloatField()

    def __str__(self):
        return self.category


class Room(models.Model):
    number = models.IntegerField()
    beds = models.IntegerField()
    capacity = models.IntegerField()
    category = models.ForeignKey(
        RoomCategory, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f'{self.number}. Beds = {self.beds} People = {self.capacity}'


class Booking(models.Model):
    PAYMENT_STATUSES = (
        ('COM', 'PAYMENT_COMPLETE'),
        ('INC', 'PAYMENT_INCOMPLETE'),
        ('PAR', 'PAYMENT_PARTIALLY_COMPLETE'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()
    payment_status = models.CharField(max_length=3, choices=PAYMENT_STATUSES)

    def __str__(self):
        return f'From = {self.check_in.strftime("%d-%b-%Y %H:%M")} To = {self.check_out.strftime("%d-%b-%Y %H:%M")}'

    def get_cancel_booking_url(self):
        return reverse_lazy('hotel:CancelBookingView', args=[self.pk, ])

class Person(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()

hotel/forms.py
from django import forms
from datetime import datetime
from django.core.exceptions import ValidationError
from .models import RoomCategory, Person

#  input_formats=["%Y-%m-%dT%H:%M", ],


class AvailabilityForm(forms.Form):
    # CATEGORY_CHOICES = [(x.category, x.category)
    #                     for x in RoomCategory.objects.all()]

    check_in = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M", "%Y-%m-%dT%H:%M%Z"], widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    check_out = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M", "%Y-%m-%dT%H:%M%Z"], widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    room_category = forms.ModelChoiceField(
        queryset=RoomCategory.objects.all())
    #  widget=forms.Select(attrs={"class": "mdb-select md-form"})

    def check_working_hours(self, start, end):
        check_in = self.cleaned_data.get('check_in')
        check_out = self.cleaned_data.get('check_out')
        # This ensures that check_in and check_out are between start and end of your working hours.
        if not(check_in < start and check_out < end):
            raise ValidationError(
                "Times beyond working hours, please enter value within working hours")
        else:
            return self.cleaned_data


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

hotel/views.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, redirect
from django.views.generic import ListView, FormView, View, DeleteView
from django.urls import reverse, reverse_lazy
from .models import Room, Booking, RoomCategory, Person
from .forms import AvailabilityForm, PersonForm
from hotel.booking_functions.availability import check_availability
from hotel.booking_functions.find_total_room_charge import find_total_room_charge
from hotel.booking_functions.get_random_person_name_email import get_random_person_name_email
from django.contrib.auth.decorators import login_required

import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
import environ


import datetime
import json


import stripe
stripe.api_key = 'sk_test_51Hu0AzH60lA1oSoomphzz4KWIOkf3fyNb6xKnMTLtZuqrYsafvJvMOQXhqxqOV0vy7EkWSuJxV3GxH5q899R8M8l00MDvjRsHl'

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

environ.Env.read_env()


# Create your views here.

class BookingFormView(View):
    def get(self, request, *args, **kwargs):
        if "check_in" in request.session:
            s = request.session
            form_data = {
                "check_in": s['check_in'], "check_out": s['check_out'], "room_category": s['room_category']}
            # booking_form_data = self.request.session['booking_form_data']
            # booking_form_data = dict(booking_form_data)
            # form_data2 = {
            #     "check_in": "2021-01-01T20:27:00+00:00",
            #     "check_out": "2021-01-02T20:27:00+00:00",
            #     "room_category": "NON-AC"
            # }
            form = AvailabilityForm(request.POST or None, initial=form_data)
            # print(form)
        else:
            form = AvailabilityForm()
        return render(request, 'booking_form.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = AvailabilityForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            # print('data_from_form = ', data)

            # if self.request.user.is_anonymous:
            # def default(o):
            #     if isinstance(o, (datetime.date, datetime.datetime)):
            #         return o.strftime("%Y-%m-%dT%H:%M")

            # def jsonify_datetime(d):
            #     return json.dumps(
            #         d,
            #         sort_keys=True,
            #         indent=1,
            #         default=default
            #     )

            # print('storing_in_session =>', data['check_in'].strftime(
            #     "%Y-%m-%dT%H:%M"), data['check_out'].strftime("%Y-%m-%dT%H:%M"), data['room_category'])

            request.session['check_in'] = data['check_in'].strftime(
                "%Y-%m-%dT%H:%M")
            request.session['check_out'] = data['check_out'].strftime(
                "%Y-%m-%dT%H:%M")
            request.session['room_category'] = data['room_category'].category
            request.session['amount'] = find_total_room_charge(
                data['check_in'], data['check_out'], data['room_category'])
            # return redirect(reverse('account_login'))
            return redirect('hotel:CheckoutView')
        return HttpResponse('form not valid', form.errors)


# def RoomListView(request):
#     room = Room.objects.all()[0]
#     room_categories = dict(room.ROOM_CATEGORIES)
#     room_values = room_categories.values()
#     room_list = []

#     for room_category in room_categories:
#         room = room_categories.get(room_category)
#         room_url = reverse('hotel:RoomDetailView', kwargs={
#                            'category': room_category})

#         room_list.append((room, room_url))
#     context = {
#         "room_list": room_list,
#     }
#     return render(request, 'room_list_view.html', context)


class BookingListView(ListView):
    model = Booking
    template_name = "booking_list_view.html"

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            booking_list = Booking.objects.all()
            return booking_list
        else:
            booking_list = Booking.objects.filter(user=self.request.user)
            return booking_list

    # def get_context_data(self, **kwargs):
    #     room = Room.objects.all()[0]
    #     room_categories = dict(room.ROOM_CATEGORIES)
    #     context = super().get_context_data(**kwargs)
    #     context


class RoomDetailView(View):
    def get(self, request, *args, **kwargs):
        print(self.request.user)
        category = self.kwargs.get('category', None)
        form = AvailabilityForm()
        room_list = Room.objects.filter(category=category)

        if len(room_list) > 0:
            room = room_list[0]
            room_category = dict(room.ROOM_CATEGORIES).get(room.category, None)
            context = {
                'room_category': room_category,
                'form': form,
            }
            return render(request, 'room_detail_view.html', context)
        else:
            return HttpResponse('Category does not exist')

    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        room_list = Room.objects.filter(category=category)
        form = AvailabilityForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data

        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)

        if len(available_rooms) > 0:
            room = available_rooms[0]

            booking = Booking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out']
            )
            booking.save()
            message = Mail(
                from_email='dhabaledarshan@gmail.com',
                to_emails='dhabalekalpana@gmail.com',
                subject='Sending from hotelina',
                html_content='<strong>Sending from hotelina</strong>')
            try:
                sg = SendGridAPIClient(env.str('SG_KEY'))
                response = sg.send(message)
                print(response.status_code)
                print(response.body)
                print(response.headers)
                print('SENT!!!')
            except Exception as e:
                print(e)
            return HttpResponse(booking)
        else:
            return HttpResponse('All of this category of rooms are booked!! Try another one')


class CancelBookingView(DeleteView):
    model = Booking
    template_name = 'booking_cancel_view.html'
    success_url = reverse_lazy('hotel:BookingListView')


class CheckoutView(View):

    def get(self, request, *args, **kwargs):
        person_form = PersonForm()
        context = {
            "person_form": person_form,

        }
        return render(request, 'checkout.html', context)

    def post(self, request, *args, **kwargs):
        person_name, person_email = get_random_person_name_email()

        customer = stripe.Customer.create(
            name=person_name,
            email=person_email
        )
        person = Person.objects.create(
            name=person_name,
            email=person_email
        )
        person.save()
        try:
            stripe.api_key = 'sk_test_51Hu0AzH60lA1oSoomphzz4KWIOkf3fyNb6xKnMTLtZuqrYsafvJvMOQXhqxqOV0vy7EkWSuJxV3GxH5q899R8M8l00MDvjRsHl'
            checkout_session = stripe.checkout.Session.create(
                success_url="http://127.0.0.1:8000/success",
                cancel_url="http://127.0.0.1:8000/cancel",
                payment_method_types=["card"],
                line_items=[
                    {
                        'price_data': {
                            'currency': 'inr',
                            'unit_amount': int(request.session['amount'])*100,
                            'product_data': {
                                'name': request.session['room_category'],

                            },
                        },
                        'quantity': 1
                    },

                ],
                mode="payment",
            )

            context = {
                'person': person,
                'checkout_id': checkout_session.id,
                'amount': request.session['amount'],
                'room_image': '',
                'room_name': request.session['room_category'],
                'amount': request.session['amount'],
                'check_in': request.session['check_in'],
                'check_out': request.session['check_out'],
            }
            print('chkout_context = ', context)

            return render(request, 'checkout_confirm.html', context)
        except Exception as e:
            print('failed , ', request.session)
            return render(request, 'failure.html', {'error': e})


def success_view(request):

    return render(request, 'success.html')


def cancel_view(request):
    return render(request, 'cancel.html')


def contact_us(request):
    return render(request, 'contact_us.html')

hotel/templates/booking_cancel_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'hotel/css/room_detail_view.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'hotel:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}
                <h2>Are you sure you wanna cancel this Booking? Details-</h2>
                <h3>{{booking.room.number}}{{booking.get_room_category}} {{booking}}</h3>
                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Cancel the Booking</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

hotel/templates/booking_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Marina Beach Hotel</title>

    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"> -->
    <!-- Bootstrap core CSS -->
    <link href="{% static 'hotel/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <!-- <link href="{% static 'hotel/css/mdb.min.css' %}" rel="stylesheet"> -->
    <!-- Your custom styles (optional) -->
    <!-- <link href="{% static 'hotel/css/style.css' %}" rel="stylesheet"> -->
    <link rel="stylesheet" href="{% static 'hotel/css/marina_beach_landing.css' %}"/>
  </head>
  <body>
      <div class="nav">
        <h3 id="logo">Marina Beach</h3>
        <!-- <ul class="navlist">
          <a href="/marina_beach_amenties.html">Amenties</a>
        </ul> -->
      </div>
    
    <div
      class="d-flex flex-column align-items-center justify-content-center check_availability"
    >
    
      <div class="headings m-4">
        <h1>Marina Beach</h1>
        <h1>Hotel</h1>
      </div>

      <div id="search-bar" style="color: #fff;">
          <form method="POST"
          class="search-form m-0 container"
          action=""
        >
        {% csrf_token %}


        
        <div class="date-row row">

          <div
            class="form-group d-flex justify-content-space-between col-sm-6 "
          >
          {{form.check_in.errors}}
            <label class="mr-2" for="{{form.check_in.id_for_label}}">From:</label>
            {{form.check_in}}
          </div>

          <div class="form-group d-flex justify-content-space-around  col-sm-6 ">
            {{form.check_out.errors}}
            <label for="{{form.check_out.id_for_label}}">To: </label>
            {{form.check_out}}
          </div>
        </div>
          
        <div class="room-row row">
          {{form.room_category.errors}}
          <label for="{{form.room_category.id_for_label}}">Room Category ::</label>
          {{form.room_category}}
        </div>
          <div class="form-group row mw-50 m-2">
            <button class="btn btn-primary col-12  mw-50 " type="submit">
              Find Room
            </button>
          </div>
          </form>

        
      </div>
          
        <!-- <img id="search-bar-img" src="./static/svg/search_bar.svg" alt="" /> -->
      </div>
    </div>
     <!-- SCRIPTS -->
  <!-- JQuery -->
  <!-- <script type="text/javascript" src="{% static 'hotel/js/jquery.min.js' %}"></script> -->
  <!-- Bootstrap tooltips -->
  <!-- <script type="text/javascript" src="{% static 'hotel/js/popper.min.js' %}"></script> -->
  <!-- Bootstrap core JavaScript -->
  <!-- <script type="text/javascript" src="{% static 'hotel/js/bootstrap.min.js' %}"></script> -->
  <!-- MDB core JavaScript -->
  <!-- <script type="text/javascript" src="{% static 'hotel/js/mdb.min.js' %}"></script> -->

  </body>
</html>

hotel/templates/booking_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking List</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'hotel/css/booking_list_view.css' %}">
</head>

<body>
    <div class="content">
        <div class="header">
            <div class="headings">
                <h1>Your Bookings</h1>
                <h2>Welcome dear {{user}}</h2>
            </div>
            <div class="home">
                <!-- Div 1: Back to Home -->
                <div class="home">
                    <a href="{% url 'hotel:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
                </div>
            </div>

        </div>

        <div class="bookings">
            {% for booking in booking_list %}
            <div class="booking">
                <img src="https://images.unsplash.com/photo-1560067174-c5a3a8f37060?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80"
                    alt="">
                <div class="category">
                    <h2>{{booking.get_room_category}} Suite</h2>
                </div>
                <div class="from">
                    <h3>From: {{booking.check_in}}</h3>
                </div>
                <div class="to">
                    <h3>To: {{booking.check_out}}</h3>
                </div>
                <div class="beds">
                    <h3>Beds: {{booking.room.beds}}</h3>
                </div>
                <div class="capacity">
                    <h3>Capacity: {{booking.room.capacity}}</h3>
                </div>
                <div class="cancel"><a href="{{booking.get_cancel_booking_url}}" class="invisible"><i
                            class="far fa-2x fa-times-circle"> Cancel
                            Booking</i></a></div>

            </div>
            {% endfor %}
        </div>
</body>

</html>

hotel/templates/cancel.html
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

hotel/templates/checkout.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Checkout Demonstration for Hotel Management System</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico'%}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'allauth/vendor/bootstrap/css/bootstrap.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'allauth/fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'allauth/fonts/Linearicons-Free-v1.0.0/icon-font.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'allauth/vendor/animate/animate.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'allauth/vendor/css-hamburgers/hamburgers.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'allauth/vendor/animsition/css/animsition.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'allauth/vendor/select2/select2.min.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'allauth/vendor/daterangepicker/daterangepicker.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'allauth/css/util.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'allauth/css/main.css'%}">
  <link rel="stylesheet" href="{%static 'hotel/css/checkout.css' %}">
  </head>
  <body>
    <div class="limiter">
      <div class="container-login100" style="background-image: url('{% static 'allauth/images/bg-01.jpg'%}');">
        <div class="wrap-login100 p-l-110 p-r-110 p-t-52 p-b-33">
          <form class="signup login100-form validate-form flex-sb flex-w" method="POST" action="">
            {% csrf_token %}
            {% if redirect_field_value %}
              <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
            {% endif %}
            <h2 class="login100-form-title login-register-strike"> login / register. </h2> 
            <h1 class="login100-form-title p-b-40">
              {% trans 'Just Name and Email'%}
            </h1>
            <blockquote class="info">NOTE: You will <strong>NOT</strong> be charged money.&#13;
              So you can continue and test the app! Cheers &#x1f603; 
            </blockquote>

            
            <div class="p-t-31 p-b-9">
              <label for="id_name" class="txt1">
                {% trans 'Name' %}
              </label>
            </div>
            <div class="wrap-input100 validate-input" data-validate = "Name is required">
              <input class="input100" type="text" name="name" placeholder="Name ( Not Required )"  id="id_name">
              <span class="focus-input100"></span>
            </div>
            
            <div class="p-t-13 p-b-9">
              <label for="id_email" class="txt1" style="display: inline;">
                {% trans 'Email' %}
              </label>
            </div>
            <div class="wrap-input100 validate-input" data-validate = "Email is required">
              <input class="input100"  type="email" name="email" placeholder="Email ( Not Required ) "  id="id_email" >
              <span class="focus-input100"></span>
            </div>
    
         
    
            <div class="container-login100-form-btn m-t-27">
              <button type="submit" class="login100-form-btn">
                {% trans 'Randomize Data and Continue' %}
              </button>
            </div>
          </form>
          <p class="p-t-15"> P.S. This form generates random data so your data is <strong>NOT</strong> publicly visible! </p>

        </div>
      </div>
    </div>
    
    
    <div id="dropDownSelect1"></div>
    
    <!--===============================================================================================-->
    <script src="{% static 'allauth/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'allauth/vendor/animsition/js/animsition.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'allauth/vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'allauth/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'allauth/vendor/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'allauth/vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'allauth/vendor/daterangepicker/daterangepicker.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'allauth/vendor/countdowntime/countdowntime.js' %}"></script>
    <!--===============================================================================================-->
    <!-- <script src="{% static 'allauth/js/main.js' %}"></script>    -->
  </body>
  
</html>

hotel/templates/checkout_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkout Confirmation for Hotel Management System</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <link rel="stylesheet" href="{% static 'hotel/css/checkout_confirm.css' %}">
    <!-- <link rel="stylesheet" href="../static/hotel/css/checkout_confirm.css"> -->
</head>
<body>
  <div class="container">
    <section class="info">
      <p class="warning"> You will <strong>NOT BE CHARGED</strong> money. But still don't enter actual credit/debit card data </p>

      <h3>Card Number : </h3>
      <h2> 4242 4242 4242 4242 </h2>
      <p>CVV number, name and email can be random.</p>
      <p class="small">(Dummy Data for successful payment)</p>

  </section>
  <section class="booking">
    <div class="booking-details">
      <p>Name: {{person.name}}</p>
      <p>Email: {{person.email}}</p>
      <p>$ {{amount}}</p>
      <p>{{room_name}} Suite</p>
      <p>Check In : {{check_in}}</p>
      <p>Check Out : {{check_out}}</p>
    </div>
      <button id="checkout_btn">Checkout</button>
  </section> 

  </div>
   
   
    
    
</body>
<script>
    const checkout_id = `{{ checkout_id }}`; //Getting checkout_id from Django context.

    var stripe = Stripe("pk_test_51Hu0AzH60lA1oSooKBHVwQkZ3afq3ST2RISi3oc9G35vFQUQSMUESSorx6Sd700QYz5cY5M3Pyxf9mwZVk1nBPGu00LPxShanC");
    var checkoutButton = document.getElementById("checkout_btn");
    checkoutButton.addEventListener("click", function () { 

      stripe.redirectToCheckout({
        sessionId:`${checkout_id}` //Passing in the checkout_id variable.
      })
      .then(function(result) {
        if (result.error) {
            alert(result.error.message);
          }
      })
      .catch(function (error) {
          console.error("Error:", error);
        })
    });
  </script>
</html>

hotel/templates/contact_us.html
<h1> contact-us</h1>

hotel/templates/room_detail_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'hotel/css/room_detail_view.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'hotel:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_in">Check In : </label>
                    <input type="datetime-local" id="id_check_in" name="check_in">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_out">Check Out : </label>
                    <input type="datetime-local" id="id_check_out" name="check_out">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Book the Room</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>